before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle
- source setup-build-id

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

stages:
- build
- deploy
- status-report

build:
  stage: build
  tags:
  - docker
  - mobile
  image: gitlab.open-xchange.com:4567/mobile/build/container/flutter:0.1
  script:
  - tools/build.triggerBuild.sh
  artifacts:
    paths:
    - build/app/outputs/apk/release/*.apk
    - ./.current-build-id

deploy:
  stage: deploy
  tags:
  - docker
  - mobile
  image: gitlab.open-xchange.com:4567/mobile/build/container/flutter:0.1
  dependencies:
  - build
  script:
  - tools/deploy.uploadToHockey.sh
  artifacts:
    paths:
    - ./.current-build-id

status-report-success:
  stage: status-report
  tags:
  - docker
  - mobile
  image: gitlab.open-xchange.com:4567/mobile/build/container/flutter:0.1
  script:
  - post-ticket-comment -s success
  when: on_success

status-report-failure:
  stage: status-report
  tags:
  - docker
  - mobile
  image: gitlab.open-xchange.com:4567/mobile/build/container/flutter:0.1
  script:
  - post-ticket-comment -s failure
  when: on_failure
