before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle
- source setup-build-id

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

stages:
- build
- deploy

build:
  stage: build
  tags:
  - docker
  - mobile
  image: gitlab.open-xchange.com:4567/mobile/build/container/flutter
  script:
  - tools/build.triggerBuild.sh
  artifacts:
    paths:
    - build/app/outputs/apk/release/*.apk
    - ./.current-build-id

deploy:
  stage: deploy
  tags:
  - docker
  - mobile
  image: gitlab.open-xchange.com:4567/mobile/build/container/flutter
  dependencies:
  - build
  script:
  - tools/build.deploy.sh
  artifacts:
    paths:
    - ./.current-build-id